version: '2'

services:
  web:
    image: python:3.8.1-alpine3.11
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r ./requirements.txt && flask run --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
